#!/bin/bash
INTERFACE=$1
ACTION=$2

case "$ACTION" in
  up|down|vpn-up|vpn-down)
    logger "sing-box: network event $ACTION on $INTERFACE, restarting"
    /home/vladimir/vpn/sing.sh restart
    ;;
esac
